-- =============================================================================
-- 000_base_schema.sql
-- Relational base: chat_sessions, chat_logs (no vectors — RAG lives in Zilliz).
-- Run on a fresh Supabase Postgres project, or use full_schema_empty_database.sql.
-- Next:      001_app_users.sql
-- Order:     FRESH_INSTALL_ORDER.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS chat_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid REFERENCES chat_sessions(id),
  user_question text,
  bot_response text,
  provider varchar,
  latency_ms int,
  cost_estimated float,
  handled_by_layer int,
  processed_for_learning boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);
