-- =============================================================================
-- 002_ingestion_file_state.sql
-- Ingest checkpoint table (idempotent Python ingest vs Supabase).
-- Run after: 005_chat_sessions_metadata.sql
-- Next:      008_analyze.sql
-- Order:     FRESH_INSTALL_ORDER.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS ingestion_file_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  mtime_ms BIGINT NOT NULL,
  size BIGINT NOT NULL,
  content_hash TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);
