-- =============================================================================
-- Fresh empty database — canonical one-file install (idempotent).
--
-- Vector storage (knowledge_base, embeddings) has moved to Zilliz Cloud.
-- This schema covers only relational tables: chat, auth, and ingestion state.
--
-- Apply: pnpm db:schema  (repository root) or cd apps/api && pnpm db:schema
-- Or paste this entire file into Supabase SQL Editor.
-- =============================================================================

-- ----- 000_base_schema -----
CREATE TABLE IF NOT EXISTS chat_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid REFERENCES chat_sessions(id),
  user_question text,
  bot_response text,
  provider varchar,
  latency_ms int,
  cost_estimated float,
  handled_by_layer int,
  processed_for_learning boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- ----- 001_app_users (JWT login; mirrors supabase/schema/001_app_users.sql) -----
CREATE TABLE IF NOT EXISTS app_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  password_hash text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT app_users_email_unique UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_app_users_email_lower ON app_users (lower(email));

COMMENT ON TABLE app_users IS 'Local app accounts; create rows via scripts/seed-user.js or INSERT with bcrypt hash.';

ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;

-- ----- 004 + 005 chat_sessions (title, sidebar) -----
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS title TEXT;
CREATE INDEX IF NOT EXISTS idx_chat_sessions_title ON chat_sessions(title);
COMMENT ON COLUMN chat_sessions.title IS 'AI-generated conversation title (max 40 chars)';

ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE OR REPLACE FUNCTION set_chat_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_chat_sessions_updated_at ON chat_sessions;
CREATE TRIGGER trg_chat_sessions_updated_at
BEFORE UPDATE ON chat_sessions
FOR EACH ROW
EXECUTE FUNCTION set_chat_sessions_updated_at();

UPDATE chat_sessions
SET updated_at = COALESCE(updated_at, created_at, NOW())
WHERE updated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_pin_updated
ON chat_sessions(user_id, is_pinned DESC, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_logs_session_created_desc
ON chat_logs(session_id, created_at DESC);

-- ----- ingestion_file_state (ingest checkpoint; kept for Supabase-side idempotency) -----
CREATE TABLE IF NOT EXISTS ingestion_file_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  mtime_ms BIGINT NOT NULL,
  size BIGINT NOT NULL,
  content_hash TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Planner stats
ANALYZE chat_sessions;
ANALYZE chat_logs;
ANALYZE app_users;
